audit_header: false
title: Atlanta Real Estate Video Blog with Melida Potts
description: Our mission at The Potts Realty Team is to be your best resource for Atlanta real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The The Potts Realty Team, your professional Atlanta Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Website 
    url: https://homes-4-atlanta.com/
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Melida Potts
  title:
  license_number:
  about_markdown: |
    Melida Has 24 Years in Atlanta real estate. Selling over 1,000 Homes, with more than $100 million in sales. That is more than 14 times that of the average agent in Atlanta. Melida has sold in all types of markets – up market, down market, flat market. You get more product & market knowledge, more accurate pricing, proven market strategies, and stronger negotiating power.

    Melida’s average market time has been 25 days compared to the Atlanta agents average of 149 days on the market. When you’re serious about selling fast nobody sells homes faster than Melida. Melida sells 3 homes in the same amount of time it takes the typical agent to sell one. List to sales price ratio is 94.4%. For example, for every $100,000, Melida will get $94,400 for you.
  brand: The Potts Realty Team
  brokerage:
  market: Atlanta
  address: 1733 Mount Vernon Road Dunwoody, Georgia 30338
  phone: 770-396-6100
  phone_type:
  phone2:
  phone2_type:
  email: mpotts@youneedresults.com
  url: http://www.homes-4-atlanta.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://homes-4-atlanta.com/home-evaluation
  second_CTA_text: Home Search
  second_CTA_URL: https://homes-4-atlanta.com/searchatl

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Atlanta Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://homes-4-atlanta.com/home-evaluation

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Atlanta Home?"
    CTA_text2: "Search the entire MLS for your Atlanta home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://homes-4-atlanta.com/searchatl

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/Potts-Realty-125990740875653/
  linkedin_url: https://www.linkedin.com/in/melida-potts-b1b4bb11
  youtube_url: https://www.youtube.com/channel/UCKfmWDTUYj5RRVlIq8T6OFg
  twitter_url: https://twitter.com/PottsRealty
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Atlanta Real Estate Podcast with Melida Potts'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Atlanta Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Potts Realty Team - your professional Atlanta Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Atlanta, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Melida Potts'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 20
  hero_text: Atlanta Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#0f1d76'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#0f1d76'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
